### ISSUE TITLE
Object stucks while editing splits

### ISSUE THREAD

**Issue by EuPhobos** [sdementen/piecash#155]
Thie problem while trying edit existing splits, in there accounts appear "None" objects, and i have error:
```
Traceback (most recent call last):
  File "test.py", line 77, in <module>
    book.save()
  File "/usr/local/lib/python3/dist-packages/piecash/core/book.py", line 270, in save
    self.session.commit()
  File "/home/prot/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/prot/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/prot/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/home/prot/.local/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3/dist-packages/piecash/core/book.py", line 214, in validate_book
    tx.validate()
  File "/usr/local/lib/python3/dist-packages/piecash/core/transaction.py", line 145, in validate
    if self.transaction.currency == self.account.commodity:
AttributeError: 'NoneType' object has no attribute 'currency'
```
I'm attach simple script and simple book to reproduce the problem
[test.zip](https://github.com/sdementen/piecash/files/5906068/test.zip)

**Comment by sdementen** [comment]
You've spotted a bug that I need to fix.

**Comment by sdementen** [comment]
hi @EuPhobos , could you check with the branch https://github.com/sdementen/piecash/tree/fix-validation-deleted-objects if the adjusted script below (I have fixed some issue with balancing the splits) works as expected ?

```
#!/usr/bin/python3

import piecash,decimal

book = piecash.open_book("book.sqlite3", readonly=False)

#RUB = book.currencies(mnemonic="RUB")


for s in book.accounts(fullname="Unsorted").splits:
	print(s.transaction.description, s.transaction.currency, s.value)
	split = s
	break


if type(split) == piecash.core.transaction.Split:
	trans = split.transaction
	val = split.value

	acc = book.accounts(fullname="Expenses:Other")
	trans.description = "[edited] "+trans.description

	new_split = []
	
	for i in range(10):
		new_split.append( piecash.Split(
			account=acc,
			value=-decimal.Decimal(str(100)),
			transaction=trans,
			memo=i
		))
	
	new_split.append( piecash.Split(
		account=book.accounts(fullname="My:Bank"),
		value=val,
		transaction=trans
	))
	new_split.append( piecash.Split(
		account=book.accounts(fullname="Unsorted"),
		value=0,
		transaction=trans
	))
	print(trans.splits)
	print(new_split)
	trans.splits[:] = new_split
	print(trans.splits)



print('---')

for s in trans.splits:
	print(s.quantity, s.value, s.account.name)

print(trans.currency)
print(acc.commodity)

print('---')

#book.delete(split)

for s in book.accounts(fullname="My:Bank").splits:
	print(s.transaction)

print('---')

for s in book.accounts(fullname="Unsorted").splits:
	print(s.transaction)

print('---')

for s in book.accounts(fullname="Expenses:Other").splits:
	print(s.transaction)

#print(book.track_dirty())

#book.flush()
book.save()
book.close()

```

**Comment by EuPhobos** [comment]
Yes, now it save in book, but "None" still rhere, and the transaction still appears inside the account where it should not be, although it is empty, without any currency.
![piecash1](https://user-images.githubusercontent.com/3438730/113500728-5f50d080-9531-11eb-97bf-63711d16a074.png)
![piecash2](https://user-images.githubusercontent.com/3438730/113500730-5fe96700-9531-11eb-8ce1-9dafe526ca78.png)
Can we somehow delete empty transactions?

**Comment by sdementen** [comment]
You can remove the split with 0 value from the list of the splits. It was not clear for me why you were adding this zero value split in
```
	new_split.append( piecash.Split(
		account=book.accounts(fullname="Unsorted"),
		value=0,
		transaction=trans
	))
```

**Comment by EuPhobos** [comment]
> It was not clear for me why you were adding this zero value split in
Thats i try somehow to delete transaction %)

Now, that is perfectly work for me! Thank you!
